Month 12/step 1
HebrinJ/algos pull request #1
Opened 2024-02-02 16:48 UTC by HebrinJ

2024-02-02 18:39 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Была проделана огромная работа 🔥.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы все алгоритмы.

### **Но есть несколько замечаний, которые нужно исправить:**

- "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE;

- По чек-листу: классы, описывающие работу структур данных, должны быть вынесены в отдельные файлы в папке соответствующего компонента (Просто перенесите их из утилит, в папку с соответствующей страницей).

- По чек-листу: функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, должны быть вынесены в отдельные файлы utils.ts в папке соответствующего компонента (Просто перенесите их из утилит, в папку с соответствующей страницей);

- Последовательность фибоначчи:

  - Нужно чтобы последовательность начиналась с 1, а не с 0.

  - Вы должны реализовать функцию `getFibonacciNumbers`, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи. Это утилитарная функция, поэтому она должна находится в `utils`, в той же папке, что и алгоритм, т.е. в `fibonacci-page`.

- Стек:

  - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма.

- Очередь:

  - По чек-листу, должно быть так: во время анимации алгоритма на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма.

- Связный список:

  - <https://disk.yandex.com/i/bnI-OrNgNjH8Lg> - Нужно подправить верстку, чтобы она соответствовала макету: <https://disk.yandex.com/i/jedNKbQ8SdXsNw>;

  - При добавлении/удалении элемента по индексу, значение должно перепрыгивать по списку до искомого индекс. Советую ещё раз ознакомится с заданием на проект, там всё описано. <https://disk.yandex.com/i/t7C-rdxk175aYQ>

  - При добавлении/удалению по индексу, вы должны проверять, "существует" ли такой индекс вообще. <https://disk.yandex.com/i/aGswKMoknmMxOA>. Кнопки не должны быть активны;

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const cash = useRef<Record<number, number>>({ 0: 0, 1: 1 });
**Можно лучше:**

не совсем понимаю зачем вам первичные данные.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          <Input value={input} type={'number'} min={0} max={19} isLimitText={true} placeholder='Выберите число' onChange={event => {onChange(event.currentTarget.value)}}/>
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +              return <div key={uuidv4()} className={style.circleBox}>
**Можно лучше:**

старайтесь не использовать `uuidv4()` в качестве `key`, рекомендую генерировать ключи за пределами компонента, чтобы избежать пересоздания ключей при каждом рендеринге.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    let setTail = (item: string, index: number) => getElementForFrame<string>(item, index, ElementStates.Default, null, 'tail' );
**Можно лучше:**

тут уже можно использовать `const`, т.к. далее вы не перезаписываете функцию.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    let setTail = (item: string, index: number) => getElementForFrame<string>('', index, ElementStates.Changing, null, <Circle letter={item} state={ElementStates.Changing} isSmall={true}/> );
**Можно лучше:**

тут уже можно использовать `const`, т.к. далее вы не перезаписываете функцию.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +        let setExtra = (item: string, index: number) => getElementForFrame<string>(item, index, ElementStates.Changing );
**Можно лучше:**

Здесь и далее. В похожих местах

тут уже можно использовать `const`, т.к. далее вы не перезаписываете функцию.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +          <Input maxLength={4} isLimitText={true} value={inputValue} onChange={event => onInputValueChange(event.currentTarget.value) }/>
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/queue-page/queue-page.tsx
> +        <Input type='text' maxLength={4} isLimitText={true} onChange={event => { onChange(event.currentTarget.value) }} value={input} extraClass={style.input} />
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/queue-page/queue-page.tsx
> +          })
**Можно лучше:**

возможно, стоит заранее промапить массив, и добавить туда нужные поля, чтобы разделить логику и `jsx`.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/sorting-page/sorting-page.tsx
> +  // 0 - Сортировка выбором, 0 - Сортировка пузырьком
Вы хотели сказать 0 и 1?

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/sorting-page/sorting-page.tsx
> +    } else if (sortType === 1) {
**Можно лучше:**

а тут может быть ещё 1 sortType? Если нет, то можно просто `else`. написать))

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/sorting-page/sorting-page.tsx
> +    let timeout = setInterval(() => {
**Можно лучше:**

Тут лучше подойдёт `const`

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/stack-page/stack-page.tsx
> +        <Input type='text' maxLength={4} isLimitText={true} onChange={event => {onChange(event.currentTarget.value)}} value={input} extraClass={style.input} />
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/components/string/string.tsx
> +          <Input value={input} type='text' isLimitText={true} maxLength={11} onChange={event => {onChange(event.currentTarget.value)}}/>
**Надо исправить:**

"Магические" значения лучше вынести в константу.

2024-02-02 18:39 UTC, ArslanMustafin commented on src/utils/fibon.ts
> +}
**Надо исправить:**

По чек-листу вы должны реализовать функцию `getFibonacciNumbers`, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи. Это утилитарная функция, поэтому она должна находится в `utils`, в той же папке, что и алгоритм, т.к. в `fibonacci-page`.

А также рекомендую написать функцию, следующим образом: 

```js
export function getFibonacciNumbers(count: number) {
  const fibonacciNumbers = [1, 1];
  for (let i = 2; i <= count; i++) {
    const a = fibonacciNumbers[i - 1];
    const b = fibonacciNumbers[i - 2];
    fibonacciNumbers.push(a + b);
  }
  return fibonacciNumbers;
}
```

2024-02-03 13:47 UTC, HebrinJ commented
Исправлены большая часть замечаний. Некоторые замечания "можно лучше" не исправил, просто потому что уже не успеваю к сроку.

2024-02-03 16:38 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все обязательные замечания были исправлены;

2024-02-06 12:06 UTC, merged